Catalin/pcchair 66/job details screen
PC-Chair-Fight/project-frontend pull request #12
Opened 2021-11-24 12:20 UTC by cata-b

Added the job details screen and made it adapt to different screen widths.

2021-11-24 18:59 UTC, darius-calugar requested changes

2021-11-24 18:59 UTC, darius-calugar commented on lib/modules/job/widgets/job_card.widget.dart
> +                      ].map((url) => JobImage(url: url)).toList())),
Cred ca totusi ar trebui sa implementam si apelurile API + logica tot pe branch-ul asta. Chiar daca blocam practic progresul pe story inca cateva zile.

2021-11-24 18:59 UTC, darius-calugar commented on lib/modules/job/widgets/job_details.widget.dart
> +        BidderCardWidget(),
Si aici as pefera sa avem clasele de servicii + providere implementate (sau cel putin definite cu functii care returneaza mock data)

2021-11-24 19:00 UTC, darius-calugar commented
![image](https://user-images.githubusercontent.com/50340991/143298395-840d1319-9702-437a-8980-de51be67fd93.png)
Ai overflow be bidder card

2021-11-25 17:02 UTC, cata-b commented on lib/modules/job/widgets/job_details.widget.dart
> +        BidderCardWidget(),
631ee56

2021-11-25 17:02 UTC, cata-b commented on lib/modules/job/widgets/job_card.widget.dart
> +                      ].map((url) => JobImage(url: url)).toList())),
8c8c7e8

2021-11-25 17:33 UTC, darius-calugar approved these changes

2021-11-28 08:21 UTC, AndrewBarzu approved these changes

2021-11-28 10:05 UTC, merged