[WIP] Initial commit
PC-Chair-Fight/project-frontend pull request #8
Opened 2021-11-08 21:25 UTC by vlad101vlad

2021-11-10 08:58 UTC, darius-calugar commented on lib/modules/job/widgets/jobCard.widget.dart
> +    );
In general se pun virgule dupa majoritate parantezelelor ca sa poti da auto-format (Ctrl+Alt+L) la cod si sa nu stai sa identezi manual tot.
Daca dai autoformat fara virgule o sa se transforme codul in ceva de genul
```
 return Center(child: Card( child: Column(child: 
)));
```
which gets unreadable fast :))
Daca auto-format iti pune 2 paranteze inchise una dupa alta cel mai probabil trebuie sa pui o virgula intre ele.

2021-11-11 18:20 UTC, darius-calugar commented on lib/modules/job/widgets/main.widget.dart
> +  }
In general doar ecranele ar trebui sa aiba ca root un scaffold. Asta cum e widget normal ar trebui sa tina o lista de card-uri sau ceva similar.
In felul in care e implementat acum ai:
`JobMainScreen -> Scaffold -> Center -> JobMain -> Scaffold -> JobCardWidget -> ...`
Nu are logica sa ai un scaffold definit ca si copil al altui scaffold.
Eu as schimba in ceva de genul:
`JobMainScreen -> Scaffold -> JobMain -> ListView/Column/etc... -> [JobCard] -> ...`

2021-11-11 18:20 UTC, darius-calugar commented on lib/modules/job/widgets/jobCard.widget.dart
> +
Vad ca ai facut widget-urile stateful si ecranele stateless.
Stateless = Widget care nu isi manage-uieste state-ul (toate field-urile lui sunt finale)
Stateful = Widget care isi manage-uieste state-ul printr-un State class (in state class poti avea field-uri non final si se le modifici cu `setState(() {...})`)

Cel mai simplu e sa pastrezi un widget stateless pana cand ajungi in punctul in care ai nevoie de un field non-final in el.

Ex.
JobMainScreen - Stateful
- nu are field-uri, dar in general widget-urile care se ocupa de apeluri API sunt stateful (poveste mai lunga)
- cheama fetchJobs() din JobsProvider in initState() {...}
- initializeaza un JobMain cu lista de jobs luata din JobsProvider

JobMain - Stateless
- final List<Job> (primit in constructor de la JobMainScreen)

JobCard - Stateless
- final Job (primit in constructor de la JobMain)

2021-11-20 11:48 UTC, darius-calugar requested changes
In loc sa las comment-uri in mai multe locuri am facut un [PR](https://github.com/PC-Chair-Fight/project-frontend/pull/9) cu sugestii de schimbari.
- Am schimbat numele la fisiere/widgets ca sa se potriveasca cu restul
- Am schimbat unele widget-uri din Stateful in Stateless ca sa mai scad din complexitatea codului (daca un widget nu are field-uri non-final atunci nu are de ce sa fie stateful)

Daca vrei poti sa dai merge direct la PR in branch-ul tau sau poti sa schimbi doar ce crezi tu ca ii nevoie.
Pe langa schimbarile astea ar trebui sa avem string-urile trecute in `l10n/intl_en.arb` (inafara de tot ce e placeholder/mock evident :) ). te poti uita cum s-a facut treaba asta in celelalte ecrane de login/register.
Cu partea de responsiveness & adaptiveness nu are rost sa iti bati capul acum. O sa o rezolv eu pe alt branch. Deci layout-ul poate sa ramana asa cum e.

Dintre toate astea tin mortis sa avem macar string-urile trecute in l10n. La celelalte schimbari poti sa le dai discard daca nu consideri ca is ok.
Dupa ce termini da-mi re-request review si iti dau approve.

2021-11-20 14:07 UTC, cata-b requested changes

2021-11-20 14:07 UTC, cata-b commented on lib/generated/l10n.dart
> +  }
This is a generated file, please add your localization data to lib/l10n/intl_en.arb

2021-11-20 14:54 UTC, darius-calugar approved these changes

2021-11-20 14:55 UTC, cata-b approved these changes

2021-11-20 15:47 UTC, merged